# Generated by Django 4.2.7 on 2023-12-02 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='taxes',
            field=models.ManyToManyField(to='payments.tax'),
        ),
    ]
