# Generated by Django 4.2.7 on 2023-12-04 16:19
from django.db import migrations
from django.contrib.auth import get_user_model


def populate_db(apps, schema_editor):
    items = [
        {
            'name': 'test_item',
            'description': 'test_description',
            'price': 2000,
        },
        {
            'name': 'test_item_2',
            'description': 'test_description_2',
            'price': 3000,
        }
    ]
    Item = apps.get_model('payments', 'Item')
    Discount = apps.get_model('payments', 'Discount')
    Tax = apps.get_model('payments', 'Tax')

    User = get_user_model()
    User.objects.create_superuser(username='admin', email='admin@example.com', password='superuser')

    for item in items:
        Item.objects.create(
            name=item['name'],
            description=item['description'],
            price=item['price']
        )
    Discount.objects.create(
        duration='once',
        percent_off=10.0
    )
    Tax.objects.create(
        display_name='Sales Tax',
        inclusive=True,
        percentage=20.0
    )


class Migration(migrations.Migration):
    dependencies = [
        ('payments', '0006_discount_order_discount'),
    ]

    operations = [
        migrations.RunPython(populate_db),
    ]
